### ISSUE TITLE
Text coloring on hex values are two different colors

### ISSUE THREAD

**Issue by aeschli** [MagicStack/MagicPython#112]
_From @Fiskelord on November 20, 2017 10:7_

- VSCode Version: 1.18.1
- OS Version: Windows 10

Steps to Reproduce:
1. Open python file, as an example
2. Write "someVariable = 0x2564"
3. See that "0x" is not the same color as "2564"

Reproduces without extensions: Yes

_Copied from original issue: Microsoft/vscode#38767_

**Comment by chbk** [comment]
That's a feature, check the screenshot in the readme:
![](https://camo.githubusercontent.com/67d8c8fa28f03f13123e6d9a9b410e19a6c39f67/68747470733a2f2f6d61676963737461636b2e6769746875622e696f2f4d61676963507974686f6e2f6578616d706c652e706e67)
You have to change your syntax highlighting theme to change the color.

**Comment by 1st1** [comment]
@chbk is correct, this is not a bug.

**Comment by wesinator** [comment]
This is the only python highlighting I have seen that exhibits this behaviour.
It looks better if the prefix is the same color IMO

**Comment by elprans** [comment]
As mentioned above, which colors to use for which scopes is a prerogative of the color theme and/or user preferences, not the grammar spec.  The goal of MagicPython is to provide fine scope resolution so that there _is_ an option to highlight the prefix differently for those of us who prefer it that way.
