### ISSUE TITLE
Suggestion: Improved PEP8 syntax

### ISSUE THREAD

**Issue by jbiason** [MagicStack/MagicPython#18]
One thing an improved VIM syntax does is proper alignment of variables and parameters in functions. For example, entering the following sequence in VIM:

```
def f(a, b, c, <enter>d):<enter>pass
```

I get

```
def f(a, b, c,
      d):
    pass
```

On the other hand, if I do the same thing in Atom, I get

```
def f(a, b, c,
d):
pass
```

Also, the VIM syntax does this while typing, no need to call some "reparagraph" command.

It would be nice if such feature was available to Atom (and maybe Sublime, but since I'm using VIM and Atom... ;) )

**Comment by 1st1** [comment]
We might be able to fix the indentation after `):`, but I don't think that we can fix it inside the parens.  So it will be something like this:

      def f(a, b, c,
      d):
          pass

Please give us some time to experiment.

**Comment by brianmhunt** [comment]
FWIW, here's a vim plugin that I think nails this (one of the very few editors that does):

- https://github.com/hynek/vim-python-pep8-indent

**Comment by ChrisBarker-NOAA** [comment]
"proper" pyton-friendly indenting would indeed be very, very nice. It is handled well by Peppy:

http://peppy.flipturn.org/

about which says "Autoindenting of source code, including a regex-based autoindenter based on KDE's Kate"

Also -- IIRC, the Emacs Python mode did a really nice job -- but it's been years since I"ve used that.

My preferences for indenting:

For contiuation after an non-closed paren, PEP 8 supports a LOT of variations on styles. But what' I"ve most often seen, at least for funciton call and defnintions with lot sof arguments is what was suggested in this issue:

```
def f(a, b, c,
      d):
    pass
```

but I personally, prefer, once there is too much to fit on one line, to put them all on their own line, and aligned with the opening parens:

```
def f(a,
      b,
      c,
      d):
    pass
```
This looks kind of silly in this example, but this example would all fit on one line anyway. But if you have a lot or parameters, particularly keyword parameters, then it really make sense:

```
def f(param1,
      param2,
      kwparam1=some_value,
      kwparam2=some_other_value,
     )
```

And these lists can get  a lot longer. I find it a lot easier to figure out what the parameters are if they each get their own line.

Perhaps an option to select one or the other of these styles -- or you leave it up to the user -- wherever they put the \n, it lines things up properly. But I think aligning with the opening parens makes the most sense. 

Also: have the same behavior for continuation lines for unclosed brackets for lists, tuples, dicts,,,,

While we are at it -- I'd really like the <tab> key to "do the right thing"

hitting <tab> ANYWHERE on the line means: " indent this line correctly"
it will then put the curser at the end of the indentation.

(and, of course, an explicit tab (\t) character is NEVER put in anywhere!)

If the cursor is within the indentation zone, then 
<backspace> means: "remove one level of indentation"
and the cursor is put at the end of the indentation

In python, of course, there are multiple levels of indentation that might be legal. But these guidelines make it work well:

After hitting either <tab> (anywhere on the line) or <delete> (with the cursor in the indentation space):
  - The indentation will always be in a legal state. (i.e if you are using 4 spaces per indent (which you always should!) and it is not a continuation line, the indent will always be a multiple of four spaces)
 - the cursor will be left at the end of the indentation space
     - this lets you reduce the level of indentation easily and obviously with the <backspace> key.

I've found this approach really makes it a lot faster and easier to have correct indentation of my code -- and not just Python!

**Comment by ChrisBarker-NOAA** [comment]
One other thought -- you could probably have <tab> bound to "autoindent' when there is more than one line selected. IT would then apply the indentation rules to all the lines, in such as way as not to change the pythonic meaning. So <tab> would always mean "indent this correctly"

**Comment by daniel-pittman** [comment]
I came here to report the same issue, where indent-after-'(' is wrong.  (and, yes, Emacs gets it right; that's what I miss it from.)  subscribing.

**Comment by 1st1** [comment]
I'm going to close this issue. I think that formatting/editing rules are outside of what MagicPython is doing/capable of doing.  This should really be handled by an editor-specific extension, not by a syntax highlighter.

**Comment by ChrisBarker-NOAA** [comment]
If all Magic Python does is syntax highlighting, then yes, this is not the place for it.

But a "proper" Python mode would include things like this.

If anyone can suggest a good place to add this code to Sublime I'd love to hear it.
