### ISSUE TITLE
Exception colouring discrepancy

### ISSUE THREAD

**Issue by mattst** [MagicStack/MagicPython#180]
Thanks for your excellent plugin.

* **Editor name and version**: Sublime Text 3176
* **Platform**: Linux
* **Color scheme**: My minor modifications of Boxy Tomorrow
* **MagicPython version**: 1.1.1

There is a discrepancy with colouring for exception names.

In the first method below, `set_directory_contents()`, all the exception names are coloured in the keyword (?) colour, those being `FileNotFoundError, NotADirectoryError, PermissionError, and Exception`.

But in the second method, `get_xwindow_ids()`, only `FileNotFoundError` is while `subprocess.TimeoutExpired` is not.

Note: The same problem persists with other colour schemes tested, e.g. Monokai.

![ScreenshotMagicPythonExceptions](https://user-images.githubusercontent.com/835623/56802556-42290880-6818-11e9-82a7-3457dd4a4c02.png)

**Comment by vpetrovykh** [comment]
Thanks for your feedback! We're glad that you like the plugin.

Currently we only highlight builtin exceptions, that is to say, literally, the exceptions that appear in the module `builtins`. The reasoning is that you get them no matter what, no particular module needs to be imported, etc. We don't, however, attempt to introspect the rest of the standard library and highlight all of the other exceptions there. The reasoning is that everything else that requires an explicit import is only special in certain context (namely when it had been imported), but is not in any way special (or builtin) otherwise. To illustrate the point, consider the module `re`. It contains, among other things, the function `search`. With a name as generic as this, it would be misleading to highlight it as a builtin in all cases. However, detecting whether or not this particular instance of `search` has been imported from the `re` module is far beyond the scope of a simple higlighter and requires full-blown static code analysis.

**Comment by mattst** [comment]
I see, that sounds totally reasonable to me. Thanks for letting me know. I had assumed that the `subprocess` module had been left out, or not yet added.

**Comment by vpetrovykh** [comment]
You're welcome.

**Comment by joolius** [comment]
How about (optionally) highlighting the first word after the keyword "except"?
