### ISSUE TITLE
modification to #member-access repository

### ISSUE THREAD

**Issue by stroupbslayen** [MagicStack/MagicPython#188]
I'm working with VSCode, would it be possible to get a scope name for `member-access`? It might just be personal preference but it's nice when themes are able to take advantage of when they're used.

## Default
![default](https://imgur.com/ZAMr2T4.png)

## Named member-access
![named](https://i.imgur.com/pVmNXaz.png)

It can be taken a bit further by adding another repository for it to check against. I only have a few hours of textMate exposure so I'm sure there are better ways of doing this. I don't have a lot of experience with regex either so most of this I just bogarted from the `source.js` file since it supports what I'm trying to do.

[Here's a gist of my modded MagicPython that was used by VSCode](https://gist.github.com/stroupbslayen/88c12fe56270d16a034ae4b70aaa3462) The added repository is called `class-call`

And an example of what that produces

![modded_source](https://i.imgur.com/olZDWI9.gif)

**Comment by vpetrovykh** [comment]
I would probably go with adding a `meta.member.access.python` to all the syntax rules that start with a `.`. The other `meta` scopes can be used to distinguish whether this is a method or attribute, etc. Generally this has the advantage of covering a sufficiently base case so that if we have some more special differentiation of the actual kinds of member access, those don't need to replicate the scoping logic.
