### ISSUE TITLE
No kernal for language python found

### ISSUE THREAD

**Issue by hugeme** [MagicStack/MagicPython#41]
Hello,

I have the same issue:

https://github.com/nteract/hydrogen/issues/201

I disabled the default `language-python`  and add MagicPython add {"MagicPython": "python"}
or {"MagicPython":"python3"} 
 to Language Mappings in the Hydrogen settings. However the kernel cant be found. With `language-python` enabled and MagicPython disabled it works.

![magic](https://cloud.githubusercontent.com/assets/18237090/15217022/eef42a16-1859-11e6-9f6f-29adf0c963af.jpg)
* **ATOM  1.7.3**:
* **MAC OS X El Capitan 10.11.4**:
* **MagicPython version 0.5.9**:
* **Hydrogen version 0.9.0 **:

**Comment by 1st1** [comment]
Seems like Hydrogen can be configured to support MagicPython, right?

**Comment by hugeme** [comment]
Are you asking me :)? I would say so!

**Comment by lgeiger** [comment]
I reproduced this issue.

If you add `{"python": "magicpython"}` to your language mappings everything should work fine.

This setting is usually used to map a kernel language name to atom's grammar name. Since MagicPython changes atom's grammar name this setting has to be applied the other way round.

You can also use the kernel mapping setting instead. Just add `{"magicpython": "Python 2"}` there.

**Comment by hugeme** [comment]
@Igeiger thank you! It works!
