### ISSUE TITLE
Include Magic Pythons tmLanguage directly into VS Code

### ISSUE THREAD

**Issue by DonJayamanne** [MagicStack/MagicPython#49]
* **Editor name and version**: VS Code
* **Platform**: All
* **MagicPython version**: Latest

I'm looking at improving the (out of the box) syntax highlighting for python in Visual Studio Code. Currently VS Code is using the tmLanguage file from [TextMate's Python bundle](https://github.com/textmate/python.tmbundle). However the tmLanguage file provided by Magic Python seems to be far better.

Do you have any concerns with me trying to include the tmLanguage file from Magic python directly into VS Code?

**Comment by 1st1** [comment]
I think it's a great idea! Couple of points/questions on the integration:

1. I recommend you to include MagicPython as is, so that it's easier for you to keep it up to date.

2. We intend to continue to support and update MP, and to keep this repo as an upstream for code changes, PRs, and issues.  All three editors will only benefit from that.

3. We'd also like to keep MP available as a separate package, so that users can always use the cutting edge version.

**Comment by DonJayamanne** [comment]
@1st1 , thanks for the response.
