### ISSUE TITLE
Cannot install MagicPython on latest vscode 1.6

### ISSUE THREAD

**Issue by zkanda** [MagicStack/MagicPython#59]
First I want to say thank you for creating this. I tried installing it on latest vscode and I got an error.

Error is here:
```
Couldn't find a compatible version of MagicPython with this version of Code.
```

**Comment by vpetrovykh** [comment]
Thanks for letting us know. While we're looking into this, you may want to know that the since version 1.5 VSCode uses MagicPython as a default highlighter for Python, so you should get all of the benefits without the need to install it separately. Obviously, the version of the highlighter that VSCode uses by default lags somewhat behind our releases, but for most use-cases it doesn't matter.

**Comment by Spareo** [comment]
I have the same issue.

**Comment by 1st1** [comment]
I've created an issue on VSCode tracker: https://github.com/MagicStack/MagicPython/issues/59

**Comment by 1st1** [comment]
Guys, it seems that 1f8b9eddfef4cf5ce76033e8b5b09a9e3979b4c1 has fixed the installation error. Please try installing 0.5.17.

**Comment by Spareo** [comment]
That did the trick for me, thank you!

**Comment by zkanda** [comment]
This has been fix for me, closing.
