### ISSUE TITLE
Keyword "is" not colorized in if condition

### ISSUE THREAD

**Issue by DonJayamanne** [MagicStack/MagicPython#69]
* **Editor name and version**: VS Code (1.7.2)
* **Platform**: OS X
* **Color scheme**: Dark (Default)
* **MagicPython version**: 0.6.0
* **A sreenshot**:
<img width="204" alt="screen shot 2016-11-29 at 3 50 48 pm" src="https://cloud.githubusercontent.com/assets/1948812/20697239/b11b6db8-b64b-11e6-9182-dcd802e7a9c4.png">

* **5-10 lines of surrounding code**:

The keyword ```is``` is not colorized.
```python
if a is None:
```

Similarly keywords ```and``` and ```or``` are also not highlighted.

Original issue: https://github.com/DonJayamanne/pythonVSCode/issues/556

**Comment by vpetrovykh** [comment]
The keywords `is`, `and` and `or` are all assigned the scope "keyword.operator.logical.python". If they are not highlighted in a particular color scheme that is likely a choice of the color scheme (such as maybe not highlighting operators). The highlighter package itself does not dictate colors, it categorizes the code so that a color scheme (and some other tools) can be applied to it base don the categories. Try some of the variants of the color scheme you like and see if any of them produce a better result for you.

**Comment by 1st1** [comment]
Hi Don,

Yeah, @vpetrovykh is right, we had this very issue reported several times before. This is an issue of the "Dark+" color schema. FWIW other operators aren't highlighted as well. 

Looking color schema JSON file, I see that it only highlights `keyword.control` scope, but not `keyword.operator`. In fact, it doesn't highlight any `operator` scope at all.

I've created a PR to fix this in VSCode: https://github.com/Microsoft/vscode/pull/16196

**Comment by aeschli** [comment]
We could give `keyword.operator.logical.python` the keyword color. But the suggested patch #16196 is not what we want, as it impacts coloring across all other languages.

Note that when making changes to the default themes you also need to run the theming tests:
`./script/test-integration.sh` to see the changes to other languages.
