### ISSUE TITLE
Incorrect highlighting when using new-style string formatting and a % sign.

### ISSUE THREAD

**Issue by fpierfed** [MagicStack/MagicPython#7]
Hi, I have just installed MagicPython in Sublime Text 3 and already love it. I have noticed a small inconsistency in the highlighting of strings like these

    print('This happens {:.02f}% of the times'.format(percent))

See the result below:
<img width="523" alt="screen shot 2015-10-20 at 12 20 25" src="https://cloud.githubusercontent.com/assets/495436/10605688/5317234e-7725-11e5-9711-5547dc1273e7.png">

In this case, of course, the % sign is not part of the formatting, just like the space and the following o.

**Comment by 1st1** [comment]
This is because `"%    s" % 123` and `%o` are valid in Python -- so we highlight both new and old formatting...

**Comment by fpierfed** [comment]
I agree that it is a tricky situation. In the example above, however, it seems to me that the correct behavior would have been to highlight ```{:.02f}``` only and leave ```% o``` alone. Discriminating this in code would require looking at the whole line and seeing that we have a call to .format without a % operator...

**Comment by vpetrovykh** [comment]
Looking at the whole line is not a viable strategy. In principle, you're never guaranteed that `.format` will even be on the same line, so it requires an infinite lookahead, which cannot be implemented. Having inconsistent highlighting based on the presence of `.format` on the same line is also undesirable (not to mention tricky due to quoting, escaping and comments potentially having `.format` in them). There is also a fair amount of code where `.format` does not appear on the same line as the string at all (example taken from [here](https://github.com/python/cpython/blob/master/Lib/inspect.py#L2768)):
```
msg = '{arg!r} parameter is positional only, ' \
      'but was passed as a keyword'
msg = msg.format(arg=param.name)
raise TypeError(msg) from None
```
Since we cannot reliably tell which formatting is actually going to be used, we highlight both kinds to help spot issues like this:
```
>>> '% of the time "{token}" has been seen: % 10d' % 42
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: not enough arguments for format string
```

**Comment by 1st1** [comment]
(see also 11342d44d179aa993e12941a170ecafd5bae25d6)
