### ISSUE TITLE
String formatting with escape characters and other symbols

### ISSUE THREAD

**Issue by gandhis1** [MagicStack/MagicPython#73]
I've encountered some strange formatting behavior. Here are two screenshots below that show the issue.

* **Editor name and version**: Visual Studio Code - PythonVSCode
* **Platform**: Microsoft Windows
* **Color scheme**: Monokai
* **MagicPython version**: TBD

I see no reason why this datetime format should be highlighted.

![syntax1](https://cloud.githubusercontent.com/assets/21064086/22532785/7cb1b624-e8b7-11e6-9854-266f26f94fdd.PNG)

This is a literal string, so escape characters shouldn't be highlighted.

![syntax2](https://cloud.githubusercontent.com/assets/21064086/22532729/0271315a-e8b7-11e6-943d-616ec0076312.PNG)

**Comment by vpetrovykh** [comment]
The first is an instance of old style formatting (Python 2 compatibility). E.g. things like `'%d' % 30`.

The second is a feature to highlight regular expressions. Regular expressions make heavy use of raw strings in Python and visually parsing regular expressions is a nightmare without decent highlighting. If that bothers you, you can use semantically equivalent raw strings using `R'this is also a raw string'`.

Compare the following:
```python
dir = r'Q:\SP_Analytics\ABS_CDO\IA_v_PIMCO\20160630 ...'
dir = R'Q:\SP_Analytics\ABS_CDO\IA_v_PIMCO\20160630 ...'
```

The reason why lower case r-strings were taken as regular expression by default was largely due to a couple of already existing highlighters that established that convention and has no other significance.

**Comment by gandhis1** [comment]
Makes sense. I wish they would deprecate the old, ugly, printf-esque syntax. And what you mention on RegEx is interesting, seems like something that ought to be codified in a PEP with a new, unique prefix. Maybe something like _x_ such as x'\d{2,4}'...

In any case, thanks for explanation. So this is a non-issue.

**Comment by vpetrovykh** [comment]
One reason why regular expressions are not codified with their own prefix is that the standard library uses strings as input to produce regular expressions. Unlike some languages (e.g. JavaScript) Python does not have regular expression _literals_.

Typically you would use the string with regular expression specification as input to something like `re.compile(reg_exp_spec)`.

**Comment by vpetrovykh** [comment]
Speaking of old and ugly formatting. If you use Python 3.6 or above you can use f-strings. They are generally more intuitive and less bulky than other formatting styles, yet they are similar enough to "new style" format strings that it's not too hard to mentally switch to them.
```python
str = f"Here is variable foo multiplied by 3: {foo * 3}"
# compare to
str = "Here is variable foo multiplied by 3: {}".format(foo * 3)
```
