### ISSUE TITLE
Inconsistent Highlighing of All-Caps Identifiers

### ISSUE THREAD

**Issue by alcarithemad** [MagicStack/MagicPython#78]
* **Editor name and version**: Sublime Text 3, stable build 3126
* **Platform**: MacOS
* **Color scheme**: Monokai
* **MagicPython version**: 1.0.7
* **A sreenshot**:
![highlighting](https://cloud.githubusercontent.com/assets/538427/24480555/df2f40ec-1499-11e7-9317-24e6d50688c9.png)

All-caps identifiers whose second character is not in A-Z don't get the same color as all-caps identifers that do. From a cursory glance at the source, I think this is `constant.other.caps.python`.

This really bugs me, because the screenshot above was extracted from a 30-entry enum and that's the only entry that isn't purple.

Thoughts?

**Comment by 1st1** [comment]
We're working on a fix :)

**Comment by vpetrovykh** [comment]
Good catch! And the fix is in the next version (1.0.8).

The short version of the update is that you can put any amount of digits between the upper-case letters and still have a `constant.other.caps.python`. The longer version of the reasoning can be seen in here #42, if you're curious about more details.

**Comment by 1st1** [comment]
1.0.8 is now available.
