### ISSUE TITLE
Github highlights escape sequences in raw strings. 

### ISSUE THREAD

**Issue by milesrout** [MagicStack/MagicPython#82]
* **Editor name and version**: GitHub
* **Platform**: GitHub
* **Color scheme**: GitHub
* **MagicPython version**: GitHub

Github highlights escape sequences in raw strings.

**Comment by 1st1** [comment]
Screenshot?

**Comment by milesrout** [comment]
![image](https://cloud.githubusercontent.com/assets/5534373/25571855/62b4c970-2e88-11e7-80bc-187285eeed08.png)

**Comment by milesrout** [comment]
It should probably be the other way around---highlight in `'\n'.join` on line 60, don't highlight in `r'\node...'` on line 62.

**Comment by 1st1** [comment]
Right, this is because lower-case 'r' raw strings are highlighted as regexp literals, for example: https://github.com/python/cpython/blob/master/Lib/http/cookies.py#L432. This isn't a new feature, `r''` strings were highlighted as regular expressions in TextMate and Sublime Text (and thus GitHub) from the beginning.

You can use upper-case `R` prefix to get true raw-string highlighting:

```python
a = R'aaa \n aaa'
a = r'aaa \n aaa'
```

I'd say it's too late to change this.

**Comment by milesrout** [comment]
Oh that's odd. I suppose that's justifiable. What about the lack of highlighting in non-raw strings?

**Comment by 1st1** [comment]
> What about the lack of highlighting in non-raw strings?

Well, this is just a convention now in many major editors. Lower-case `r'strings'` are highlighted as regexps, upper-case `R'strings'` are highlighted as actual raw strings.

**Comment by vpetrovykh** [comment]
The *apparent* lack of highlighting of `'\n'.join` is due to the color scheme choices that GitHub made, not to the lack of distinction in the language package. Basically, you would see the string being highlighted correctly with escaped characters in other editors (like Atom or Sublime Text) with richer color schemes.

**Comment by milesrout** [comment]
Hmm, non-ideal but doesn't look like the issue is on your end. Thanks.
