### ISSUE TITLE
Incorrect highlighting on imports from all caps modules

### ISSUE THREAD

**Issue by michaelboulton** [MagicStack/MagicPython#83]
* **Editor name and version**: Sublime 3 3126
* **Platform**: Linux
* **MagicPython version**: 1.0.10

I noticed this in sublime but it also happens on github.

I understand it's considered bad to name modules in all caps but if you have a module with all caps in the name it's highlighted as if it's a constant. Example:

```python
from package.HELLO.test import x
from package.hello.test import x
```

**Comment by vpetrovykh** [comment]
The issue is that the highlighter cannot keep track of which identifiers are module names and which are not. So even if we force the highlighting of import statements to never use "constant" marker, as the result we would simply push the inconsistent highlighting further into the code body. Consider the following:
```python
import package.HELLO

...

x = package.HELLO.world()
```

So because this is a fairly unlikely scenario in the first place (going against naming conventions and good coding practices) and because we cannot fix it consistently, we're not going to attempt creating a workaround.
