### ISSUE TITLE
Integer literal problem with PEP515 syntax style

### ISSUE THREAD

**Issue by claws** [MagicStack/MagicPython#95]
MagicPython has problems identifying an integer constant that uses the PEP515 syntax style. If I change the START constant to a decimal (i.e. ``1_000_000.0``) it does not work either. I believe that both of these are valid Python PEP515 code.

* **Editor name and version**: Sublime Text 3 (Build 3126)
* **Platform**: OSX 10.12.5
* **Color scheme**: Material Theme
* **MagicPython version**: 1.0.11
* **A sreenshot**:
<img width="340" alt="screenshot-osx-py362-20170722" src="https://user-images.githubusercontent.com/1298001/28487491-98f9608a-6ed0-11e7-9c79-41366485c4c5.png">

* **5-10 lines of surrounding code**:
```python3
START = 1_000_000
STOP = 1_500_000
STEP = 15_000
print(f'{START}, {STOP}, {STEP}')
```

**Comment by 1st1** [comment]
I'm not sure I see the problem, and I don't see any on the screenshot you provided.

Look, since GitHub uses MagicPython to highlight Python code, we can check it right here:

```python
a = 1000000
a = 1000000.12
a = 1000000.12a
a = 1_000_000
a = 1_000_000_
a = 1_000_000.12
a = 1_000_000.12a
```

In the above test case, all proper literals (including the ones that follow PEP 511 style) are correctly highlighted. Improper ones, are highlighted with red background.

Trailing `_` isn't allowed by PEP 511, and Python rejects such literals.

Maybe you are having problems with some linter plugin here?

**Comment by claws** [comment]
You are correct. I still had an Anaconda setting configured for Python3.5:

```json
"python_interpreter": "/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5",
```

With that line updated to point to Python 3.6 I no longer see the linting related highlight issue - which I mistakenly attributed to MagicPython.
