### ISSUE TITLE
Function names no longer highlighted?

### ISSUE THREAD

**Issue by Delgan** [MagicStack/MagicPython#96]
Hello.

Sorry to open an issue for what is more a question than a bug report, but I confess I have a hard time understanding this.

* **Editor name and version**: Atom v1.18.0 x64
* **Platform**: Windows 10
* **Color scheme**:  One Dark _(default)_
* **MagicPython version**: 1.0.11
* **A sreenshot**: ![1500927861-screenshot](https://user-images.githubusercontent.com/4193924/28543082-ea4a1e76-70be-11e7-8ee8-a1571bd6d718.png)

-----

1. According to https://github.com/MagicStack/MagicPython/issues/2, I thought that function calls were highlighted. Is it no longer the case?
2. Why is `file` highlighted while this is neither a keyword nor a builtin?

I am very new to Atom, maybe I did something wrong.
Thank you in advance for your help.

**Comment by 1st1** [comment]
Hi @Delgan,

Highlighting depends on two things:

* syntax highlighting package (MagicPython) -- this one tokenizes your source code and assigns special "scopes" to each token

* syntax theme (One Dark in your case) -- this assigns different colors to each "scope".

> According to #2, I thought that function calls were highlighted. Is it no longer the case?

So in this case, MagicPython does assign a special scope to "my_func" in `my_func()`, but the color scheme doesn't support that scope. You can try a different color scheme, or you can fork one of the existing ones.

> Why is file highlighted while this is neither a keyword nor a builtin?

It's probably highlighted because it's a Python 2 (not Python 3) built-in function.

**Comment by Delgan** [comment]
Oh, I better understand how it works thanks to your explanations, thank you for having answered so quickly!

By selecting another theme at random (could not find a better way), I was able to observe functions highlighting just as I expected.

Again thanks for the help and all the work. 👍
